version: '3'

services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  redis:
    image: redis:5.0.8-alpine
    volumes:
      - redis-data:/data

  gwp_app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/gw-people
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

volumes:
  db-data:
  redis-data:
