version: '3'

services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  redis:
    image: redis:5.0.8-alpine
    volumes:
      - redis-data:/data

  setup:
    image: tadpreston/gwp-app-dev:latest
    env_file:
      - .env
    depends_on:
      - postgres
    command: "bundle exec rake db:prepare"

  web:
    image: tadpreston/gwp-app-dev:latest
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    command: "bundle exec puma -C config/puma.rb"

  sidekiq:
    image: tadpreston/gwp-app-dev:latest
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: "bundle exec sidekiq"

volumes:
  db-data:
  redis-data:
