apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewaypeople-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: tadpreston/gwp-app:latest
        ports:
        - containerPort: 3000
