default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432

development:
  <<: *default
  database: gw_people_development
  username: <%= ENV.fetch("DATABASE_USER") { "dbname" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "dbpassword" } %>

test:
  <<: *default
  database: gw_people_test
  username: <%= ENV.fetch("DATABASE_USER") { "dbname" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "dbpassword" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
