apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: tadpreston/gw-people:latest
        args: ["rake db:prepare"]
        env:
        - name: DATABASE_NAME
          value: "gatewaypeople_production"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgresql://gwp_db_user:fMVHbwTddAdJJzo2wA2zRVe9za7PDJxzYhCZuGhc@db-gatewaypeople-poc.cogswnczjbwx.us-east-2.rds.amazonaws.com/gatewaypeople_production?pool=5&port=5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: "db-user"
              key: "username"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"
        - name: REDIS_URL
          value: "redis-gwp-poc.b53bha.ng.0001.use2.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        - name: RAILS_ENV
          value: "production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
      restartPolicy: Never
