---
apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: rails-kube-app
spec:
  ports:
    - port: 3000
      targetPort: http-server
  selector:
    app: rails-kube-app
    tier: app
  type: LoadBalancer
